sudo: required
language: java
jdk: oraclejdk8


cache:
  directories:
  - $HOME/.m2

services:
  - docker
  - postgresql
before_script:
  - sudo sh install/install.sh 0
  - sudo sh install/install.sh 2

script:
  - ./mvnw clean package -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID jacoco:report coveralls:report
        
notifications:
  email: false
