language: java
jdk: oraclejdk8

sudo: required
services:
  - docker
  - postgresql
before_script:
  - sudo sh install/db.sh
  - sudo sh install/docker.sh

script:
  - mvn clean package
after_success:
  - mvn clean test -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID jacoco:report coveralls:report
        
notifications:
  email: false
