sudo: required
language: java
jdk: oraclejdk8

services:
  - docker
  - postgresql
before_script:
  - sudo sh install/db.sh
  - sudo sh install/docker.sh

script:
  - ./mvnw clean package
after_success:
  - ./mvnw clean test -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID jacoco:report coveralls:report
        
notifications:
  email: false
