# config context path to "/" by setting an empty string
server:
  contextPath:


spring:
  #Spring profile
  profiles: "prod"
  # JACKSON
  jackson:
    serialization:
      INDENT_OUTPUT: true
  mail:
    host: 
    port: 587
    username: "CHANGEME"
    password: "CHANGEME"
    smtp:
      protocol: smtp
      debug: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

  datasource:
    url: jdbc:postgresql://localhost/codechill
    username: code
    password: chill

  jpa:
    generate:
      ddl: true
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  file: /var/log/codechill-server.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: ERROR

app:
  dockerurl: CHANGEME
  clienturl: CHANGEME

#logging:
#  level:
#    org.springframework:
#      security: DEBUG