FROM alpine:latest

RUN apk update && apk upgrade && \
    apk add nginx && \
    apk add openjdk11-jre && \
    apk add openrc && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /run/nginx

RUN mkdir /www
RUN mkdir /config

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY codechill-server.jar /www/

RUN rc-update add nginx default

EXPOSE 80 443

CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=prod", "-Dspring.config.location=/config/application.yml", "/www/codechill-server.jar"]