FROM alpine:latest

RUN apk update && apk upgrade && \
    apk add nginx && \
    apk add openrc && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /run/nginx

RUN mkdir /opt; cd /opt; \
    wget https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz \
    && tar zxf openjdk-11.0.2_linux-x64_bin.tar.gz \
    && ln -s jdk-11.0.2 java \
    && rm -f openjdk-11.0.2_linux-x64_bin.tar.gz
ENV JAVA_HOME=/opt/java
ENV PATH="$PATH:$JAVA_HOME/bin"

RUN mkdir /www
RUN mkdir /config

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY codechill-server.jar /www/

RUN rc-update add nginx default

EXPOSE 80 443

CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=prod", "-Dspring.config.location=/config/application.yml", "/www/codechill-server.jar"]
