FROM alpine:latest

RUN apk update && apk upgrade && \
    apk add nginx && \
    apk add openrc && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /run/nginx

ENV JAVA_HOME /opt/openjdk-12
ENV PATH $JAVA_HOME/bin:$PATH

# https://jdk.java.net/
ENV JAVA_VERSION 12-ea+29
ENV JAVA_URL https://download.java.net/java/early_access/alpine/29/binaries/openjdk-12-ea+29_linux-x64-musl_bin.tar.gz
ENV JAVA_SHA256 39c22481736ae8a054fc820ad0cc3f1d9ad3f3f00d8111775573fe6d04c18bf5
# "For Alpine Linux, builds are produced on a reduced schedule and may not be in sync with the other platforms."

RUN set -eux; \
	\
	wget -O /openjdk.tgz "$JAVA_URL"; \
	echo "$JAVA_SHA256 */openjdk.tgz" | sha256sum -c -; \
	mkdir -p "$JAVA_HOME"; \
	tar --extract --file /openjdk.tgz --directory "$JAVA_HOME" --strip-components 1; \
	rm /openjdk.tgz; \
	\
# https://github.com/docker-library/openjdk/issues/212#issuecomment-420979840
# https://openjdk.java.net/jeps/341
	java -Xshare:dump; \
	\
# basic smoke test
	java --version; \
javac --version

RUN mkdir /www
RUN mkdir /config

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY codechill-server.jar /www/

RUN rc-update add nginx default

EXPOSE 80 443 8080

CMD ["java", "-jar", "-Dspring.profiles.active=prod", "-Dspring.config.location=/config/application.yml", "/www/codechill-server.jar"]
